package com.example.weatherapp;

public enum WeatherTypes {
    CLOUDY, CLOUDYDAY, CLOUDYNIGHT,
    FOG,
    HAIL, HAILDAY, HAILNIGHT,
    LIGHTRAIN, LIGHTRAINDAY, LIGHTRAINNIGHT,
    MOON, SUN,
    RAINY, RAINYDAY, RAINYNIGHT,
    SHOWER, SHOWERDAY, SHOWERNIGHT,
    SNOW,SNOWDAY,SNOWNIGHT, SNOWSTORM,
    THUNDERSTORM, THUNDERSTORMDAY, THUNDERSTORMNIGHT,
    WIND, WINDDAY, WINDNIGHT
}
